apiVersion: v1
kind: ConfigMap
metadata:
  name: proxy-environment-variables
  namespace: kube-system
data:
  HTTPS_PROXY: http://${PROXY_URL}
  HTTP_PROXY: http://${PROXY_URL}
  NO_PROXY: 172.20.0.0/16,localhost,127.0.0.1,${VPC_CIDR_RANGE},169.254.169.254,.internal